# Generated by Django 3.2.4 on 2024-06-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='precio',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
