# Generated by Django 3.2.4 on 2024-06-30 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_favoritos'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favoritos',
            constraint=models.UniqueConstraint(fields=('id_flan', 'id_user'), name='unique_flan_user'),
        ),
    ]
