# Generated by Django 3.2.4 on 2024-07-02 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0005_favoritos_unique_flan_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('calificacion', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('id_flan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.flan')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
